### ISSUE TITLE
Update default dependencies

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/github-actions-base#1]
- [ ] use openjdk11 for java default
- [ ] use tagged github_changelog_generator v1.15.2. specific commit version does not work anymore with latest github API.
```
gem install github_changelog_generator -v 1.15.2
```

**Comment by tloubrieu-jpl** [comment]
@jordanpadams , @nutjob4life I found my ticket https://github.com/github-changelog-generator/github-changelog-generator/issues/864

So this version 1.15.2 did not work for us.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams The latest version is https://github.com/github-changelog-generator/github-changelog-generator/releases/tag/v1.16.1

Should we use it ?

**Comment by jordanpadams** [comment]
will revisit when we can make sure we have all our ducks in a row with https://github.com/NASA-PDS/roundup-action/issues/39 and we are ready to test it out.
