### ISSUE TITLE
As a developer, I'd like the Python template repo to build again

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/github-actions-base#10]
[I](https://github.com/nutjob4life) [merged](https://github.com/NASA-PDS/pds-template-repo-python/commit/f247a8405787fa874e587a7fa91420365241c5aa) a change from @MJJoyce that resulted in the Roundup running and [failing with this log](https://github.com/NASA-PDS/pds-template-repo-python/runs/3303898182?check_suite_focus=true). @tloubrieu-jpl found [the problem](https://github.com/NASA-PDS/pds-github-util/issues/16) in the [pds-github-util](https://github.com/NASA-PDS/pds-github-util) and fixed it 🎉 This fix [is on PyPI as version 0.22.2](https://pypi.org/project/pds-github-util/0.22.2/).

But Roundup uses the [Github Actions Base](https://github.com/NASA-PDS/github-actions-base) which calls for 0.22.0 … womp womp 😢

Please update the Github Actions Base to use 0.22.2.

**Comment by MJJoyce** [comment]
Hey, thanks @tloubrieu-jpl for figuring out what I broke and fixing it!

**Comment by nutjob4life** [comment]
Hah @MJJoyce you didn't break it! This was something from back in July. It was just a corner case that we didn't anticipate.

**Comment by MJJoyce** [comment]
oh haha, I got an email or 2 of it shouting at me so I figured I did something 😆

**Comment by tloubrieu-jpl** [comment]
actually @MJJoyce you contributed to improve the code by detecting a bug, thanks !

**Comment by jordanpadams** [comment]
@nutjob4life was this deployed? looks like I am getting the same error: https://github.com/NASA-PDS/validate/runs/3342826994?check_suite_focus=true#step:4:11443

**Comment by nutjob4life** [comment]
Yeah, I'm seeing the same error in the template repo.

It turns out pds-github-util 0.22.2 was released on June 27th.
![Screen Shot 2021-08-17 at 10 55 09 AM](https://user-images.githubusercontent.com/814813/129759998-db885f4c-a3df-47e8-a071-3a5553c0194d.png)

But the fix for the requirements-report was made on July 29th:
https://github.com/NASA-PDS/pds-github-util/commit/6e79ef843ce038d08b22365e6a9238380d3a6a40

We need a newer pds-github-util 😩

**Comment by nutjob4life** [comment]
@jordanpadams [see this comment](https://github.com/NASA-PDS/github-actions-base/issues/10#issuecomment-900422304).

Here's an idea: make the Github Actions Base always use the _latest_ pds-github-util, **and** make pds-github-util's release trigger a build/register of Github Actions Base 😁

**Comment by jordanpadams** [comment]
@nutjob4life +1. great idea! did I just see a ✋ raised to volunteer to do this?!? 😄

**Comment by nutjob4life** [comment]
@jordanpadams 🤣 yeah I guess so! 😅

**Comment by jimmie** [comment]
PDS github util remains out of date. Re-opening.

**Comment by nutjob4life** [comment]
Okay, so it looks like then to resolve this issue, we just need to release a new version of NASA-PDS/pds-github-util.

Any objections if we do that? @tloubrieu-jpl @MJJoyce? The instructions for it say it's just `git tag <version>; git push origin --tags`. Are those still correct?

Once that's done, then re-running the last action of _this_ repository should make us golden!

**Comment by MJJoyce** [comment]
+1, I think that's all we need. If no one beats me to it I'll tackle it later this week when I have PDS-time.

**Comment by nutjob4life** [comment]
Apparently Zenhub is broken and I cannot add a "blocked by" dependency to this issue: https://github.com/NASA-PDS/pds-github-util/issues/24 🤷‍♀️

**Comment by MJJoyce** [comment]
It seems that this and #14 are both blocked by an installation issue caused by NASA-PDS/pds-github-util#25

**Comment by nutjob4life** [comment]
After [a commit to this repository](https://github.com/NASA-PDS/github-actions-base/commit/54a9d80880397930e372e36d8ce24cfb6b6f5696) as well as a [commit the template repository](https://github.com/NASA-PDS/pds-template-repo-python/commit/305a2805414ee1b4ac10ba5017df6a510523fd2a), combined with [manual build and push of the Actions base](https://hub.docker.com/r/nasapds/pds-github-actions-base), I was finally able to a [successful build](https://github.com/NASA-PDS/pds-template-repo-python/actions/runs/1199263709).

Closing this off but feel free to re-open if issues re-appear.
