### ISSUE TITLE
As a developer I want to github-actions-base to pull the latest pds-github-utils release

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/github-actions-base#12]
## 💪 Motivation
See NASA-PDS/github-actions-base#10 for related discussions. We want the latest `pds-github-utils` release to get pulled into `github-actions-base`.

## ⚙️ Engineering Details
The naive "just don't install a specific tag for `pds-github-utils` approach seems reasonable enough here. Not sure if there's concerns about that. We could certainly come up with a more complicated solution but it would seemingly get us to the same-ish end point. Thoughts?

**Comment by nutjob4life** [comment]
Seems to overlap https://github.com/NASA-PDS/pds-github-util/issues/21

**Comment by nutjob4life** [comment]
Now all we need is a release of `pds-github-util` to trigger a release of `github-actions-base`! 🎉

**Comment by MJJoyce** [comment]
How in the world did I reopen this??

**Comment by nutjob4life** [comment]
😅
