### ISSUE TITLE
As a generally good individual I want to builds to be triggered by pds-github-util builds

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/github-actions-base#14]
## 💪 Motivation
See #10 for lots of details. TLDR, we want `github-actions-base` to build whenever a new release of `pds-github-util` gets tagged so magical CI things will happen without manual updates from us.

## ⚙️ Engineering Details
`pds-github-util` has an open PR (NASA-PDS/pds-github-util#22) to add an action to emit a Repository Dispatch event via https://github.com/marketplace/actions/repository-dispatch whenever a new version is tagged. We need to listen for that event so we can trigger a build as well.

**Comment by MJJoyce** [comment]
While I may be a good individual, it turns out that wasn't enough to get this fully functional. We need to modify the `repository dispatch` handling so it can spoof a version. See NASA-PDS/github-actions-base#10 for details on the issue(s).

**Comment by jordanpadams** [comment]
Moving back to ToDo

**Comment by MJJoyce** [comment]
This has been resolved. See latest build here after push of `pds-github-util`:
https://github.com/NASA-PDS/github-actions-base/actions/runs/1214609421

And the updated image on dockerhub:
https://hub.docker.com/r/nasapds/pds-github-actions-base
