### ISSUE TITLE
Fix failure of auto-deployment to DockerHub

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/github-actions-base#16]
## 🐛 Describe the bug

See https://github.com/NASA-PDS/github-actions-base/runs/3424298356?check_suite_focus=true#step:4:354

**Comment by jordanpadams** [comment]
@MJJoyce us this fixed per the tickets submitted on pds-github-util?

**Comment by MJJoyce** [comment]
Yes, resolved now. See [clean builds](https://github.com/NASA-PDS/github-actions-base/actions/workflows/triggered-stable-cicd.yaml) for reference
