### ISSUE TITLE
Python 3.8 is used by the Roundup by 3.9 by the projects—and the template repo!

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/github-actions-base#17]
## 🐛 Describe the bug

Take a look at https://github.com/NASA-PDS/pds-doi-service/runs/3626183249?check_suite_focus=true

See the problem? The `pds-doi-service` is based on the `pds-template-repo-python`, both of which use Python 3.9 features, such as type annotations using `type`-based types like `list` and `dict`. But the Roundup fails because Using `list` and `dict` in type annotations isn't supported in Python 3.8, which is what the Roundup uses.

## 📜 To Reproduce

Commit a change to `pds-doi-service` then wait 22+ minutes.

## 🕵️ Expected behavior

If the `pds-template-repo-python` and all of our other Python-based repositories are using Python 3.9, then the Roundup should too.

**Comment by MJJoyce** [comment]
+1, good catch @nutjob4life
