### ISSUE TITLE
Upgrade base image to support openjdk17 deployment

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/github-actions-base#27]
## 💡 Description

Upgrade the github-actions-base from python:3.9.7-alpine3.14 → python:3.9.16-alpine3.16

**Comment by nutjob4life** [comment]
Hi @tloubrieu-jpl it looks like [this is already done on the main branch](https://github.com/NASA-PDS/github-actions-base/commit/b29f2c6da22d7c6bdd3ea6288ec126ff28b2221d).

I think this issue should be closed since there's nothing more to be done.

**Comment by tloubrieu-jpl** [comment]
Closed by https://github.com/NASA-PDS/github-actions-base/commit/b29f2c6da22d7c6bdd3ea6288ec126ff28b2221d
